import { relative, resolve, sep } from "node:path";

/**
 * Normalize a repository-relative or logical diagnostic path to POSIX `/`.
 *
 * Use this for `SkillsetDiagnostic.path` / `outputPath`, `LintIssue.path`, and
 * `SkillsetFeatureDiagnosticError.path`. Do not pass JSON pointers, selectors,
 * or actual filesystem operands through this helper — those keep their native
 * spelling. Callers that already computed `relative(root, absolute)` should
 * still run the result through here so Windows `\` does not leak into
 * structured diagnostics.
 */
export function toLogicalDiagnosticPath(path: string): string {
  return path.replaceAll("\\", "/");
}

/**
 * Repository-relative logical diagnostic path for a source or output file.
 *
 * Computes `relative(rootPath, absolutePath)` then converts native separators
 * to `/`. The absolute argument is a filesystem operand; the return value is
 * the portable diagnostic identity.
 */
export function logicalDiagnosticPath(rootPath: string, absolutePath: string): string {
  return toLogicalDiagnosticPath(relative(rootPath, absolutePath));
}

export function resolveInside(root: string, candidate: string): string {
  const resolvedRoot = resolve(root);
  const resolved = resolve(resolvedRoot, candidate);
  const relativePath = relative(resolvedRoot, resolved);

  if (
    relativePath === "" ||
    relativePath.startsWith("..") ||
    relativePath.includes(`..${sep}`)
  ) {
    throw new Error(`skillset: refusing to operate outside repo root: ${candidate}`);
  }

  return resolved;
}

/**
 * Deterministic, locale-independent string ordering.
 *
 * `localeCompare` collates by host locale, which can reorder lock/hash inputs
 * across machines and silently change generated bytes. Comparing with `<`/`>`
 * uses UTF-16 code-unit order, which is stable everywhere.
 */
export function compareStrings(left: string, right: string): number {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

export function validateSlug(value: string, label: string): string {
  if (!/^[a-z0-9][a-z0-9-]*$/.test(value)) {
    throw new Error(
      `skillset: expected ${label} to be a lowercase slug, received ${JSON.stringify(value)}`
    );
  }

  return value;
}
