import { realpath } from "node:fs/promises";
import nodePath from "node:path";

/**
 * Normalize a repository-relative or logical diagnostic path to POSIX `/`.
 *
 * Use this for `SkillsetDiagnostic.path` / `outputPath`, `LintIssue.path`, and
 * `SkillsetFeatureDiagnosticError.path`. Do not pass JSON pointers, selectors,
 * or actual filesystem operands through this helper — those keep their native
 * spelling. Callers that already computed `relative(root, absolute)` should
 * still run the result through here so Windows `\` does not leak into
 * structured diagnostics. A literal backslash is a valid POSIX filename
 * character, so only replace separators for paths known to use Windows
 * syntax.
 */
export function toLogicalDiagnosticPath(
  path: string,
  sourceSeparator: "/" | "\\" = nodePath.sep
): string {
  return sourceSeparator === "\\" ? path.replaceAll("\\", "/") : path;
}

/**
 * Repository-relative logical diagnostic path for a source or output file.
 *
 * Computes `relative(rootPath, absolutePath)` then converts native separators
 * to `/`. The absolute argument is a filesystem operand; the return value is
 * the portable diagnostic identity.
 */
export function logicalDiagnosticPath(rootPath: string, absolutePath: string): string {
  return toLogicalDiagnosticPath(nodePath.relative(rootPath, absolutePath));
}

/**
 * Path primitives used by containment checks. Tests inject `path.win32` so
 * drive-letter and separator behavior can be proven on a POSIX host.
 */
export interface PathContainmentApi {
  readonly isAbsolute: (path: string) => boolean;
  readonly relative: (from: string, to: string) => string;
  readonly resolve: (...paths: string[]) => string;
  readonly sep: string;
}

export interface PathContainmentOptions {
  /**
   * When true, `parent` itself counts as inside. `resolveInside` leaves this
   * false so a computed write target cannot be the root directory.
   */
  readonly allowEqual?: boolean;
  readonly path?: PathContainmentApi;
}

const PARENT_SEGMENT = "..";

/**
 * True when `relativePath` is a contained descendant (or, with
 * `allowEqual`, the parent itself). Rejects `..`, `..`+separator prefixes,
 * and absolute results such as a Windows other-drive `relative()`. Accepts
 * names that merely begin with `..` (`..foo`).
 */
export function isRelativePathInside(
  relativePath: string,
  opts: PathContainmentOptions = {}
): boolean {
  if (relativePath === "") return opts.allowEqual === true;
  const api = opts.path ?? nodePath;
  if (api.isAbsolute(relativePath)) return false;
  return !isParentRelativePrefix(relativePath, api.sep);
}

/**
 * Lexical containment: `child` must stay under `parent` after `relative()`.
 * This is the OS-path write-safety check. It does not follow symlinks;
 * use {@link assertRealPathInside} when comparing realpaths.
 */
export function isPathInside(
  parent: string,
  child: string,
  opts: PathContainmentOptions = {}
): boolean {
  const api = opts.path ?? nodePath;
  return isRelativePathInside(api.relative(parent, child), opts);
}

/**
 * Resolve `candidate` against `root` and refuse anything that is not a
 * strict descendant. The root itself is refused; pass `isPathInside` with
 * `allowEqual` when a caller needs the directory as a valid target.
 */
export function resolveInside(
  root: string,
  candidate: string,
  opts: Pick<PathContainmentOptions, "path"> = {}
): string {
  const api = opts.path ?? nodePath;
  const resolvedRoot = api.resolve(root);
  const resolved = api.resolve(resolvedRoot, candidate);
  if (!isPathInside(resolvedRoot, resolved, opts)) {
    throw new Error(`skillset: refusing to operate outside repo root: ${candidate}`);
  }
  return resolved;
}

/**
 * Realpath `path` and require it to stay inside the realpath of `root`,
 * including the root itself. Returns the resolved child path.
 */
export async function assertRealPathInside(
  root: string,
  path: string,
  message?: string
): Promise<string> {
  const realRoot = await realpath(root);
  const realPath = await realpath(path);
  if (!isPathInside(realRoot, realPath, { allowEqual: true })) {
    throw new Error(message ?? `skillset: refusing to operate outside repo root: ${path}`);
  }
  return realPath;
}

/**
 * Deterministic, locale-independent string ordering.
 *
 * `localeCompare` collates by host locale, which can reorder lock/hash inputs
 * across machines and silently change generated bytes. Comparing with `<`/`>`
 * uses UTF-16 code-unit order, which is stable everywhere.
 */
export function compareStrings(left: string, right: string): number {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

export function validateSlug(value: string, label: string): string {
  if (!/^[a-z0-9][a-z0-9-]*$/.test(value)) {
    throw new Error(
      `skillset: expected ${label} to be a lowercase slug, received ${JSON.stringify(value)}`
    );
  }

  return value;
}

function isParentRelativePrefix(relativePath: string, sep: string): boolean {
  if (relativePath === PARENT_SEGMENT) return true;
  if (relativePath.startsWith(`${PARENT_SEGMENT}${sep}`)) return true;
  // Logical POSIX relatives still appear on win32 after `\` → `/` normalization.
  return sep !== "/" && relativePath.startsWith(`${PARENT_SEGMENT}/`);
}
