import { describe, expect, it } from "bun:test";
import { mkdtemp, symlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  compareNormalizedOutputTreeEntries,
  compareNormalizedOutputTrees,
  formatNormalizedTreeComparison,
  readNormalizedOutputTree,
  type NormalizedOutputTreeEntry,
} from "@skillset/core";

describe("normalized output trees", () => {
  it("enumerates nested paths in deterministic POSIX order and preserves binary bytes", async () => {
    const root = await fixture({
      "b.txt": "b\n",
      "nested/a.txt": "a\n",
    });
    await Bun.write(join(root, "asset.bin"), new Uint8Array([0, 255, 1, 2]));

    const tree = await readNormalizedOutputTree(root);

    expect(tree.entries.map((entry) => entry.path)).toEqual(["asset.bin", "b.txt", "nested/a.txt"]);
    expect([...entry(tree.entries, "asset.bin").bytes]).toEqual([0, 255, 1, 2]);
  });

  it("compares generated bytes and reports concise path-level differences", async () => {
    const left = await fixture({
      "changed.md": "left\n",
      "left-only.md": "left\n",
      "same.md": "same\n",
    });
    const right = await fixture({
      "changed.md": "right\n",
      "right-only.md": "right\n",
      "same.md": "same\n",
    });

    const comparison = await compareNormalizedOutputTrees(left, right);

    expect(comparison.equal).toBe(false);
    expect(comparison.identical).toEqual(["same.md"]);
    expect(comparison.different).toEqual(["changed.md"]);
    expect(comparison.leftOnly).toEqual(["left-only.md"]);
    expect(comparison.rightOnly).toEqual(["right-only.md"]);
    expect(formatNormalizedTreeComparison(comparison, 2)).toContain("... 1 more difference(s)");
  });

  it("canonicalizes locks and explicit structured paths while leaving target artifacts byte-based", async () => {
    const left = await fixture({
      ".skillset.lock": `{"z":1,"a":{"b":2}}`,
      "manifest.json": `{"z":1,"a":2}`,
      "report.json": `{"z":1,"a":2}`,
      "report.yaml": "z: 1\na: 2\n",
    });
    const right = await fixture({
      ".skillset.lock": `{"a":{"b":2},"z":1}`,
      "manifest.json": `{"a":2,"z":1}`,
      "report.json": `{"a":2,"z":1}`,
      "report.yaml": "a: 2\nz: 1\n",
    });

    const comparison = await compareNormalizedOutputTrees(left, right, {
      structuredJsonPaths: ["manifest.json"],
      structuredYamlPaths: ["report.yaml"],
    });

    expect(comparison.identical).toContain(".skillset.lock");
    expect(comparison.identical).toContain("manifest.json");
    expect(comparison.identical).toContain("report.yaml");
    expect(comparison.different).toEqual(["report.json"]);
  });

  it("excludes only explicit volatile paths and catches forbidden path leaks", async () => {
    const left = await fixture({
      "dist-report/index.txt": "left\n",
      "dist/index.txt": "left\n",
      ".skillset/build/tests/runs/run-1/index.json": "{}\n",
      "stable.txt": "same\n",
    });
    const right = await fixture({
      "dist-report/index.txt": "right\n",
      "dist/index.txt": "right\n",
      ".skillset/build/tests/runs/run-2/index.json": "{}\n",
      "stable.txt": "same\n",
    });

    const comparison = await compareNormalizedOutputTrees(left, right, {
      excludePathPrefixes: [".skillset/build/tests/runs/", "dist"],
    });

    expect(comparison.different).toEqual(["dist-report/index.txt"]);

    await Bun.write(join(right, "leak.txt"), `root=${right}\n`);
    await expect(
      readNormalizedOutputTree(right, { forbiddenSubstrings: [right] })
    ).rejects.toThrow("contains forbidden value");
  });

  it("compares in-memory entries for runner-produced normalized data", () => {
    const left: readonly NormalizedOutputTreeEntry[] = [
      { bytes: new TextEncoder().encode("a"), kind: "bytes", path: "a.txt" },
    ];
    const right: readonly NormalizedOutputTreeEntry[] = [
      { bytes: new TextEncoder().encode("b"), kind: "bytes", path: "a.txt" },
    ];

    const comparison = compareNormalizedOutputTreeEntries(left, right);

    expect(comparison.differences).toEqual([
      {
        detail: "bytes/bytes content differs (1 bytes vs 1 bytes, sha256 ca978112ca1b vs 3e23e8160039)",
        kind: "different",
        path: "a.txt",
      },
    ]);
  });

  it("rejects output symlinks instead of silently ignoring them", async () => {
    const root = await fixture({
      "target.txt": "target\n",
    });
    await symlink("target.txt", join(root, "linked.txt"));

    await expect(readNormalizedOutputTree(root)).rejects.toThrow(
      "normalized output tree does not support symlinks: linked.txt"
    );
  });
});

function entry(entries: readonly NormalizedOutputTreeEntry[], path: string): NormalizedOutputTreeEntry {
  const found = entries.find((candidate) => candidate.path === path);
  if (found === undefined) throw new Error(`missing ${path}`);
  return found;
}

async function fixture(files: Record<string, string>): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "skillset-normalized-tree-"));
  for (const [path, content] of Object.entries(files)) {
    await Bun.write(join(root, path), content);
  }
  return root;
}
