import {
  lstat,
  mkdir,
  readFile,
  readdir,
  rmdir,
  unlink,
  writeFile,
} from "node:fs/promises";
import path from "node:path";

import { CLI_PRESENTATION_GROUPS } from "../apps/skillset/src/cli-presentation";
import { validateCliContractParity } from "./cli-contract-parity";
import { replaceGeneratedBlock } from "./docs/markdown";
import {
  buildDocsReferenceModel,
  type CliCommandReference,
  type DocsReferenceModel,
  type ReferenceDocLink,
  type SupportReference,
} from "./docs/reference-model";

const CLI_INDEX_PATH = "docs/reference/cli/README.md";
const CLI_FLAGS_PATH = "docs/reference/cli-flags.md";
const CLI_ROOT = "docs/reference/cli";
const GENERATED_HEADER =
  "<!-- Generated by `bun run docs:generate`; do not edit directly. -->";
const SUPPORT_MATRIX_PATH = "docs/reference/support-matrix.md";

export interface DocsReferenceArtifact {
  readonly content: string;
  readonly path: string;
}

export function buildDocsReferenceArtifacts(
  model: DocsReferenceModel = buildDocsReferenceModel()
): readonly DocsReferenceArtifact[] {
  return [
    ...model.cliCommands.map((command) => ({
      content: renderCliCommandPage(command),
      path: `${CLI_ROOT}/${command.command}.md`,
    })),
    {
      content: renderSupportMatrix(model.support),
      path: SUPPORT_MATRIX_PATH,
    },
  ].toSorted((left, right) => left.path.localeCompare(right.path));
}

export async function generateDocsReferenceArtifacts(
  root: string,
  options: { readonly check?: boolean } = {}
): Promise<void> {
  const parityViolations = validateCliContractParity();
  if (parityViolations.length > 0) {
    throw new Error(
      [
        "skillset: CLI contracts are inconsistent; reference generation stopped",
        ...parityViolations.map(
          (violation) => `- ${violation.surface}: ${violation.message}`
        ),
      ].join("\n")
    );
  }
  const model = buildDocsReferenceModel();
  const artifacts = buildDocsReferenceArtifacts(model);
  for (const artifactPath of [
    CLI_INDEX_PATH,
    CLI_FLAGS_PATH,
    ...artifacts.map((artifact) => artifact.path),
  ]) {
    await assertNoSymlinkComponents(root, artifactPath);
  }
  const expectedPaths = new Set(artifacts.map((artifact) => artifact.path));
  const unexpected = (await listCliMarkdown(root)).filter(
    (artifactPath) =>
      artifactPath !== CLI_INDEX_PATH && !expectedPaths.has(artifactPath)
  );
  const unmanagedUnexpected: string[] = [];
  const generatedUnexpected: string[] = [];
  for (const artifactPath of unexpected) {
    const content = await readFile(path.join(root, artifactPath), "utf8");
    if (hasGeneratedOwnership(content)) {
      generatedUnexpected.push(artifactPath);
    } else {
      unmanagedUnexpected.push(artifactPath);
    }
  }

  const cliIndexPath = path.join(root, CLI_INDEX_PATH);
  const cliIndex = await readFile(cliIndexPath, "utf8");
  const expectedCliIndex = replaceGeneratedBlock(
    cliIndex,
    "cli-command-list",
    `\n${renderCliCommandList(model.cliCommands)}\n`
  );
  const cliFlagsPath = path.join(root, CLI_FLAGS_PATH);
  const cliFlags = await readFile(cliFlagsPath, "utf8");
  const expectedCliFlags = replaceGeneratedBlock(
    replaceGeneratedBlock(
      cliFlags,
      "cli-flag-vocabulary",
      `\n${renderCliFlagVocabulary(model)}\n`
    ),
    "cli-environment",
    `\n${renderCliEnvironment(model)}\n`
  );

  if (options.check === true) {
    const missingOrStale: string[] = [];
    for (const artifact of artifacts) {
      const current = await readTextIfExists(path.join(root, artifact.path));
      if (current !== artifact.content) missingOrStale.push(artifact.path);
    }
    if (cliIndex !== expectedCliIndex) missingOrStale.push(CLI_INDEX_PATH);
    if (cliFlags !== expectedCliFlags) missingOrStale.push(CLI_FLAGS_PATH);
    if (
      missingOrStale.length > 0 ||
      generatedUnexpected.length > 0 ||
      unmanagedUnexpected.length > 0
    ) {
      throw new Error(
        [
          "skillset: documentation reference artifacts are stale; run bun run docs:generate",
          ...missingOrStale.map(
            (artifactPath) => `- missing or stale: ${artifactPath}`
          ),
          ...generatedUnexpected.map(
            (artifactPath) => `- unexpected generated artifact: ${artifactPath}`
          ),
          ...unmanagedUnexpected.map(
            (artifactPath) => `- unexpected unmanaged artifact: ${artifactPath}`
          ),
        ].join("\n")
      );
    }
    return;
  }

  if (unmanagedUnexpected.length > 0) {
    throw new Error(
      [
        "skillset: refusing to replace unmanaged CLI reference artifacts",
        ...unmanagedUnexpected.map((artifactPath) => `- ${artifactPath}`),
      ].join("\n")
    );
  }
  for (const artifactPath of generatedUnexpected) {
    await unlink(path.join(root, artifactPath));
    await removeEmptyParents(root, path.posix.dirname(artifactPath));
  }
  for (const artifact of artifacts) {
    const outputPath = path.join(root, artifact.path);
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, artifact.content, "utf8");
  }
  await writeFile(cliIndexPath, expectedCliIndex, "utf8");
  await writeFile(cliFlagsPath, expectedCliFlags, "utf8");
}

function hasGeneratedOwnership(content: string): boolean {
  const normalized = content.replaceAll("\r\n", "\n");
  if (!normalized.startsWith("---\n")) return false;
  const frontmatterEnd = normalized.indexOf("\n---\n", 4);
  if (frontmatterEnd === -1) return false;
  return normalized
    .slice(frontmatterEnd + "\n---\n".length)
    .startsWith(`${GENERATED_HEADER}\n`);
}

async function removeEmptyParents(
  root: string,
  relativeDirectory: string
): Promise<void> {
  let current = relativeDirectory;
  while (current !== CLI_ROOT && current.startsWith(`${CLI_ROOT}/`)) {
    try {
      await rmdir(path.join(root, current));
    } catch (error) {
      if (
        error instanceof Error &&
        "code" in error &&
        ["ENOENT", "ENOTEMPTY"].includes(String(error.code))
      ) {
        return;
      }
      throw error;
    }
    current = path.posix.dirname(current);
  }
}

function renderCliCommandPage(command: CliCommandReference): string {
  const sections = command.routes.flatMap((route) => {
    const grouped = command.routes.length > 1;
    const routeHeading = grouped
      ? [`## \`skillset ${route.route}\``, "", route.summary, ""]
      : [];
    const depth = grouped ? "###" : "##";
    const usage = route.synopses.map((synopsis) => `skillset ${synopsis}`);
    const options =
      route.flags.length === 0
        ? ["This route has no route-specific options."]
        : [
            "| Option | Meaning |",
            "| --- | --- |",
            ...route.flags.map(
              (flag) =>
                `| \`${escapeTable(flag.syntax)}\` | ${escapeTable(flag.meaning)} |`
            ),
          ];
    const examples =
      route.examples.length === 0
        ? []
        : ["", `${depth} Examples`, "", "```text", ...route.examples, "```"];
    return [
      ...routeHeading,
      `${depth} Usage`,
      "",
      "```text",
      ...usage,
      "```",
      "",
      `${depth} Options`,
      "",
      ...options,
      ...examples,
      "",
    ];
  });
  return [
    "---",
    `description: ${command.description}`,
    "---",
    GENERATED_HEADER,
    "",
    `# \`skillset ${command.command}\``,
    "",
    `> Generated from Skillset's CLI presentation contract. See the [documentation system](../../development/documentation-system.md).`,
    "",
    command.summary,
    "",
    ...sections,
  ].join("\n");
}

function renderCliCommandList(
  commands: readonly CliCommandReference[]
): string {
  const groups = new Map<string, CliCommandReference[]>();
  for (const command of commands) {
    const entries = groups.get(command.group) ?? [];
    entries.push(command);
    groups.set(command.group, entries);
  }
  return CLI_PRESENTATION_GROUPS.flatMap((group) => {
    const entries = groups.get(group) ?? [];
    return [
      `## ${group}`,
      "",
      ...entries.map(
        (command) =>
          `- [\`skillset ${command.command}\`](./${command.command}.md) — ${command.summary}`
      ),
      "",
    ];
  })
    .join("\n")
    .trimEnd();
}

function renderCliFlagVocabulary(model: DocsReferenceModel): string {
  return [
    "| Flag | Family | Value | Meaning |",
    "| --- | --- | --- | --- |",
    ...model.cliFlags.map(
      (flag) =>
        `| \`${escapeTable(flag.syntax)}\` | \`${flag.family}\` | \`${flag.value}\` | ${escapeTable(flag.meaning)} |`
    ),
  ].join("\n");
}

function renderCliEnvironment(model: DocsReferenceModel): string {
  return [
    "| Variable | Contract |",
    "| --- | --- |",
    ...model.cliEnvironment.map(
      (entry) => `| \`${entry.name}\` | ${escapeTable(entry.meaning)} |`
    ),
  ].join("\n");
}

function renderSupportMatrix(support: SupportReference): string {
  const columns = ["Feature", "Feature status", ...support.targets, "Docs"];
  const rows = support.features.map((feature) => {
    const docs = feature.docs
      .map((doc, index) => `[${index + 1}](${relativeReferenceLink(doc)})`)
      .join(", ");
    return [
      feature.title,
      `\`${feature.status}\``,
      ...feature.targetSupport.map(({ status }) => `\`${status}\``),
      docs || "—",
    ];
  });
  return [
    "---",
    "description: Shows registry-owned Skillset feature status across every canonical provider target.",
    "---",
    GENERATED_HEADER,
    "",
    "# Feature Support Matrix",
    "",
    "> Generated from Skillset's feature registry. See the [documentation system](../development/documentation-system.md).",
    "",
    "Statuses are emitted verbatim from the registry. Open a feature's linked page for its evidence, qualifications, and provider-specific detail.",
    "",
    `| ${columns.map(escapeTable).join(" | ")} |`,
    `| ${columns.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escapeTable).join(" | ")} |`),
    "",
  ].join("\n");
}

function relativeReferenceLink(doc: ReferenceDocLink): string {
  let destination = path.posix.relative("docs/reference", doc.path);
  if (!destination.startsWith(".")) destination = `./${destination}`;
  return doc.fragment === undefined
    ? destination
    : `${destination}#${doc.fragment}`;
}

function escapeTable(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

async function listCliMarkdown(root: string): Promise<readonly string[]> {
  const discovered: string[] = [];
  async function visit(relativeDirectory: string): Promise<void> {
    let entries;
    try {
      entries = await readdir(path.join(root, relativeDirectory), {
        withFileTypes: true,
      });
    } catch (error) {
      if (isMissing(error)) return;
      throw error;
    }
    for (const entry of entries) {
      const relativePath = path.posix.join(relativeDirectory, entry.name);
      if (entry.isSymbolicLink()) {
        throw new Error(
          `skillset: refusing symbolic link in generated CLI reference root: ${relativePath}`
        );
      }
      if (entry.isDirectory()) {
        await visit(relativePath);
      } else if (entry.isFile() && entry.name.endsWith(".md")) {
        discovered.push(relativePath);
      }
    }
  }
  await visit(CLI_ROOT);
  return discovered.toSorted();
}

async function assertNoSymlinkComponents(
  root: string,
  relativePath: string
): Promise<void> {
  const normalized = path.posix.normalize(relativePath);
  if (
    normalized.startsWith("../") ||
    path.posix.isAbsolute(normalized) ||
    normalized !== relativePath
  ) {
    throw new Error(
      `skillset: unsafe documentation artifact path: ${relativePath}`
    );
  }
  const segments = normalized.split("/");
  let current = root;
  for (const segment of segments) {
    current = path.join(current, segment);
    try {
      const stat = await lstat(current);
      if (stat.isSymbolicLink()) {
        throw new Error(
          `skillset: refusing symbolic link in documentation artifact path: ${relativePath}`
        );
      }
    } catch (error) {
      if (isMissing(error)) return;
      throw error;
    }
  }
}

async function readTextIfExists(
  artifactPath: string
): Promise<string | undefined> {
  try {
    return await readFile(artifactPath, "utf8");
  } catch (error) {
    if (isMissing(error)) return undefined;
    throw error;
  }
}

function isMissing(error: unknown): boolean {
  return error instanceof Error && "code" in error && error.code === "ENOENT";
}
