import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import {
  SKILLSET_SCHEMA_VERSION,
  deriveSkillsetExampleArtifacts,
  deriveSkillsetJsonSchemaArtifacts,
  schemaUri,
  skillsetSchemaContracts,
} from "../packages/schema/src";
import { stringifyYaml } from "../packages/core/src/yaml";
import type { JsonRecord } from "../packages/core/src/types";
import type { SchemaJsonRecord, SchemaJsonValue } from "../packages/schema/src";

const EXAMPLE_ROOT = join("docs", "reference", "examples");
const SCHEMA_ROOT = join("docs", "reference", "schemas");
const REFERENCE_README = join(SCHEMA_ROOT, "README.md");
const GENERATED_HEADER = "<!-- Generated by `bun run schema:generate`; do not edit directly. -->";

export async function generateSchemaArtifacts(options: { readonly check?: boolean } = {}): Promise<void> {
  const artifacts = buildSchemaArtifacts();
  if (options.check === true) {
    await assertArtifactsFresh(artifacts);
    return;
  }
  await rm(SCHEMA_ROOT, { force: true, recursive: true });
  await rm(EXAMPLE_ROOT, { force: true, recursive: true });
  for (const artifact of artifacts) {
    await mkdir(dirname(artifact.path), { recursive: true });
    await writeFile(artifact.path, artifact.content, "utf8");
  }
}

export function buildSchemaArtifacts(): readonly Artifact[] {
  const artifacts: Artifact[] = [];
  for (const artifact of deriveSkillsetJsonSchemaArtifacts()) {
    artifacts.push({
      content: `${JSON.stringify(artifact.schema, null, 2)}\n`,
      path: artifact.path,
    });
  }

  const schemaArtifacts = deriveSkillsetJsonSchemaArtifacts();
  for (const example of deriveSkillsetExampleArtifacts()) {
    const contract = schemaArtifacts.find((candidate) => candidate.contractId === example.contractId);
    if (contract === undefined) throw new Error(`skillset: missing schema contract for example ${example.contractId}`);
    const diagnostics = validateAgainstSchema(example.value, contract.schema);
    if (diagnostics.length > 0) {
      throw new Error(`skillset: generated example ${example.path} does not match ${example.contractId} schema\n${diagnostics.join("\n")}`);
    }
    const comment = example.contractId === "workspace-config"
      ? `# yaml-language-server: $schema=${schemaUri("workspace-config")}\n`
      : "";
    artifacts.push({
      content: example.format === "json"
        ? `${JSON.stringify(example.value, null, 2)}\n`
        : `${comment}${stringifyYaml(example.value as JsonRecord)}`,
      path: example.path,
    });
  }

  artifacts.push({
    content: renderSchemaReadme(),
    path: REFERENCE_README,
  });

  return artifacts.sort((left, right) => left.path.localeCompare(right.path));
}

export function validateAgainstSchema(
  value: unknown,
  schema: SchemaJsonRecord,
  path = "$"
): readonly string[] {
  return validateSchemaValue(value, schema, path);
}

interface Artifact {
  readonly content: string;
  readonly path: string;
}

async function assertArtifactsFresh(artifacts: readonly Artifact[]): Promise<void> {
  const missingOrStale: string[] = [];
  for (const artifact of artifacts) {
    const current = await readTextIfExists(artifact.path);
    if (current !== artifact.content) missingOrStale.push(artifact.path);
  }
  const unexpected = findUnexpectedGeneratedArtifactPaths(
    artifacts,
    await listGeneratedArtifactFiles([SCHEMA_ROOT, EXAMPLE_ROOT])
  );
  if (missingOrStale.length > 0 || unexpected.length > 0) {
    throw new Error(
      [
        "skillset: schema artifacts are stale; run bun run schema:generate",
        ...missingOrStale.map((path) => `- missing or stale: ${path}`),
        ...unexpected.map((path) => `- unexpected generated artifact: ${path}`),
      ].join("\n")
    );
  }
}

export function findUnexpectedGeneratedArtifactPaths(
  artifacts: readonly Artifact[],
  currentPaths: readonly string[]
): readonly string[] {
  const expected = new Set(artifacts.map((artifact) => artifact.path));
  return currentPaths.filter((path) => !expected.has(path)).sort();
}

async function listGeneratedArtifactFiles(roots: readonly string[]): Promise<readonly string[]> {
  const files = await Promise.all(roots.map((root) => listFiles(root)));
  return files.flat().sort();
}

async function listFiles(root: string): Promise<readonly string[]> {
  let entries: readonly DirectoryEntry[];
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return [];
    throw error;
  }

  const files: string[] = [];
  for (const entry of entries) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...await listFiles(path));
    } else {
      files.push(path);
    }
  }
  return files.sort();
}

interface DirectoryEntry {
  readonly name: string;
  isDirectory(): boolean;
}

async function readTextIfExists(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return undefined;
    throw error;
  }
}

function renderSchemaReadme(): string {
  const schemaRows = skillsetSchemaContracts
    .map((contract) => `| \`${contract.id}\` | [\`${contract.id}.schema.json\`](./${SKILLSET_SCHEMA_VERSION}/${contract.id}.schema.json) | ${contract.description} |`)
    .join("\n");
  const exampleRows = deriveSkillsetExampleArtifacts()
    .map((example) => {
      const name = example.path.replace("docs/reference/examples/", "");
      return `| \`${example.contractId}\` | [\`${name}\`](../examples/${name}) | ${example.description} |`;
    })
    .join("\n");

  return [
    GENERATED_HEADER,
    "",
    "# Skillset Schemas",
    "",
    `Current schema artifact version: \`${SKILLSET_SCHEMA_VERSION}\`. These files are generated from \`@skillset/schema\`; edit the schema contracts and run \`bun run schema:generate\` instead of editing the artifacts directly.`,
    "",
    "## Schemas",
    "",
    `The combined schema is [\`skillset.schema.json\`](./${SKILLSET_SCHEMA_VERSION}/skillset.schema.json). Use the document-specific schemas below for editor file associations.`,
    "",
    "| Contract | Artifact | Purpose |",
    "| --- | --- | --- |",
    schemaRows,
    "",
    "## Examples",
    "",
    "The examples are generated from typed fixtures and checked against the same schema contracts before they are written.",
    "",
    "| Contract | Example | Purpose |",
    "| --- | --- | --- |",
    exampleRows,
    "",
    "## Editor Integration",
    "",
    `Workspace manifests can use the YAML language-server comment \`# yaml-language-server: $schema=${schemaUri("workspace-config")}\`. Skillset scaffolds this comment because the manifest schema is strict and should not need an extra \`$schema\` key in authored YAML.`,
    "",
  ].join("\n");
}

function validateSchemaValue(value: unknown, schema: SchemaJsonRecord, path: string): string[] {
  const diagnostics: string[] = [];
  if (schema.anyOf !== undefined) {
    const anyOf = asSchemaArray(schema.anyOf);
    if (anyOf.length > 0 && !anyOf.some((candidate) => validateSchemaValue(value, candidate, path).length === 0)) {
      diagnostics.push(`${path} must match at least one allowed shape`);
      return diagnostics;
    }
  }
  if (schema.const !== undefined && value !== schema.const) diagnostics.push(`${path} must equal ${JSON.stringify(schema.const)}`);
  if (schema.enum !== undefined) {
    const values = Array.isArray(schema.enum) ? schema.enum : [];
    if (!values.includes(value as SchemaJsonValue)) diagnostics.push(`${path} must be one of ${values.map((entry) => JSON.stringify(entry)).join(", ")}`);
  }
  validateType(value, schema, path, diagnostics);

  if (typeof value === "string") validateString(value, schema, path, diagnostics);
  if (Array.isArray(value)) validateArray(value, schema, path, diagnostics);
  if (isRecord(value)) validateObject(value, schema, path, diagnostics);
  return diagnostics;
}

function validateType(value: unknown, schema: SchemaJsonRecord, path: string, diagnostics: string[]): void {
  if (schema.type === undefined) return;
  const types = Array.isArray(schema.type) ? schema.type : [schema.type];
  if (!types.some((type) => matchesType(value, type))) {
    diagnostics.push(`${path} must be ${types.join(" or ")}`);
  }
}

function validateString(value: string, schema: SchemaJsonRecord, path: string, diagnostics: string[]): void {
  if (typeof schema.minLength === "number" && value.length < schema.minLength) {
    diagnostics.push(`${path} must be at least ${schema.minLength} characters`);
  }
  if (typeof schema.pattern === "string" && !(new RegExp(schema.pattern).test(value))) {
    diagnostics.push(`${path} must match ${schema.pattern}`);
  }
}

function validateArray(value: readonly unknown[], schema: SchemaJsonRecord, path: string, diagnostics: string[]): void {
  if (typeof schema.minItems === "number" && value.length < schema.minItems) {
    diagnostics.push(`${path} must contain at least ${schema.minItems} items`);
  }
  if (schema.uniqueItems === true && (new Set(value.map((item) => JSON.stringify(item))).size !== value.length)) {
    diagnostics.push(`${path} must contain unique items`);
  }
  if (isRecord(schema.items)) {
    for (const [index, item] of value.entries()) {
      diagnostics.push(...validateSchemaValue(item, schema.items, `${path}[${index}]`));
    }
  }
}

function validateObject(value: Record<string, unknown>, schema: SchemaJsonRecord, path: string, diagnostics: string[]): void {
  const required = Array.isArray(schema.required) ? schema.required.filter((item): item is string => typeof item === "string") : [];
  for (const key of required) {
    if (!(key in value)) diagnostics.push(`${path}.${key} is required`);
  }

  if (schema.dependentRequired !== undefined && isRecord(schema.dependentRequired)) {
    for (const [key, dependencies] of Object.entries(schema.dependentRequired)) {
      if (!(key in value) || !Array.isArray(dependencies)) continue;
      for (const dependency of dependencies) {
        if (typeof dependency === "string" && !(dependency in value)) diagnostics.push(`${path}.${dependency} is required when ${path}.${key} is set`);
      }
    }
  }

  const properties = isRecord(schema.properties) ? schema.properties : {};
  if (schema.additionalProperties === false) {
    for (const key of Object.keys(value)) {
      if (!(key in properties)) diagnostics.push(`${path}.${key} is not supported`);
    }
  }
  for (const [key, propertySchema] of Object.entries(properties)) {
    if (!(key in value) || !isRecord(propertySchema)) continue;
    diagnostics.push(...validateSchemaValue(value[key], propertySchema, `${path}.${key}`));
  }
}

function asSchemaArray(value: SchemaJsonValue | undefined): readonly SchemaJsonRecord[] {
  if (!Array.isArray(value)) return [];
  return value.filter(isRecord);
}

function matchesType(value: unknown, type: SchemaJsonValue): boolean {
  if (type === "array") return Array.isArray(value);
  if (type === "boolean") return typeof value === "boolean";
  if (type === "integer") return Number.isInteger(value);
  if (type === "number") return typeof value === "number";
  if (type === "object") return isRecord(value);
  if (type === "string") return typeof value === "string";
  if (type === "null") return value === null;
  return false;
}

function isRecord(value: unknown): value is Record<string, SchemaJsonValue> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

if (import.meta.main) {
  await generateSchemaArtifacts({ check: process.argv.includes("--check") });
}
