import { existsSync, readdirSync, statSync } from "node:fs";
import { readdir, readFile, stat } from "node:fs/promises";
import { basename, dirname, join, relative } from "node:path";

import {
  mergeRecords,
  readRecord,
  readString,
  readStringArray,
  stripSourceFrontmatter,
} from "./config";
import { validateSlug } from "./path";
import type {
  BuildGraph,
  JsonRecord,
  JsonValue,
  RenderedFile,
  ResolvedTarget,
  SourcePlugin,
  SourceSkill,
  TargetName,
} from "./types";
import { isJsonRecord, stringifyJson, stringifyMarkdown } from "./yaml";

const textEncoder = new TextEncoder();
const DEFAULT_CODEX_COLOR = "#B06DFF";

export async function renderBuildGraph(graph: BuildGraph): Promise<readonly RenderedFile[]> {
  const rendered: RenderedFile[] = [];
  rendered.push(...renderRepositoryReadmes(graph));
  rendered.push(...renderClaudeMarketplace(graph));

  for (const plugin of graph.plugins) {
    rendered.push(...(await renderPluginTarget(graph, plugin, "claude")));
    rendered.push(...(await renderPluginTarget(graph, plugin, "codex")));
  }

  return rendered.sort((left, right) => left.path.localeCompare(right.path));
}

function renderRepositoryReadmes(graph: BuildGraph): readonly RenderedFile[] {
  return [
    textFile(
      `${graph.distDir}/README.md`,
      [
        "# Generated Agent Plugins",
        "",
        "This directory is generated by `skillset` from the portable source under",
        `\`${graph.sourceDir}/\`. Rebuild it; do not hand-edit generated files.`,
        "",
        "- `claude/` contains a Claude plugin repository.",
        "- `codex/` contains a Codex plugin repository.",
        "",
      ].join("\n")
    ),
    textFile(
      `${graph.distDir}/claude/README.md`,
      [
        "# Claude Plugins",
        "",
        "Generated Claude plugin repository.",
        "",
        "- `.claude-plugin/marketplace.json` indexes the generated plugins.",
        "- `plugins/<plugin-id>/` contains each Claude plugin bundle.",
        "",
      ].join("\n")
    ),
    textFile(
      `${graph.distDir}/codex/README.md`,
      [
        "# Codex Plugins",
        "",
        "Generated Codex plugin repository.",
        "",
        "- `plugins/<plugin-id>/` contains each Codex plugin bundle.",
        "",
      ].join("\n")
    ),
  ];
}

function renderClaudeMarketplace(graph: BuildGraph): readonly RenderedFile[] {
  const plugins = graph.plugins
    .filter((plugin) => plugin.targets.claude.enabled)
    .map((plugin) => {
      const metadata = plugin.metadata;
      return mergeRecords(
        {
          name: plugin.id,
          source: `./plugins/${plugin.id}`,
          description: readString(metadata, "description") ?? plugin.id,
          version: readString(metadata, "version") ?? "0.1.0",
          author: metadata.author,
          repository: metadata.repository,
          license: metadata.license,
          keywords: metadata.keywords,
          category: metadata.category,
          strict: metadata.strict,
        },
        readRecord(plugin.targets.claude.options, "marketplace") ?? {}
      );
    });

  if (plugins.length === 0) return [];

  const root = graph.root.metadata;
  const owner = readRecord(root, "owner") ?? readRecord(root, "author") ?? {};
  const marketplace = mergeRecords(
    {
      name: readString(root, "id") ?? "galligan",
      owner,
      metadata: {
        description:
          readString(root, "description") ?? "Source-first skillset plugins by @galligan",
        version: readString(root, "version") ?? "0.1.0",
        pluginRoot: "./plugins",
        generatedBy: "galligan/agents skillset compiler",
      },
      plugins,
    },
    readRecord(graph.root.targets.claude.options, "marketplace") ?? {}
  );

  return [
    textFile(
      `${graph.distDir}/claude/.claude-plugin/marketplace.json`,
      stringifyJson(marketplace)
    ),
  ];
}

async function renderPluginTarget(
  graph: BuildGraph,
  plugin: SourcePlugin,
  target: TargetName
): Promise<readonly RenderedFile[]> {
  if (!plugin.targets[target].enabled) return [];

  const rendered: RenderedFile[] = [];
  const basePath = `${graph.distDir}/${target}/plugins/${plugin.id}`;
  const enabledSkills = plugin.skills.filter((skill) => skill.targets[target].enabled);

  rendered.push(
    textFile(
      target === "claude"
        ? `${basePath}/.claude-plugin/plugin.json`
        : `${basePath}/.codex-plugin/plugin.json`,
      stringifyJson(renderPluginManifest(graph, plugin, target, enabledSkills))
    )
  );

  for (const skill of enabledSkills) {
    rendered.push(...(await renderSkillFiles(plugin, skill, target, basePath)));
  }

  rendered.push(...(await copyPluginCompanionFiles(plugin, target, basePath)));
  return rendered;
}

function renderPluginManifest(
  graph: BuildGraph,
  plugin: SourcePlugin,
  target: TargetName,
  enabledSkills: readonly SourceSkill[]
): JsonRecord {
  const metadata = plugin.metadata;
  const targetOptions = plugin.targets[target].options;
  const base: JsonRecord = {
    name: plugin.id,
    version: readString(metadata, "version") ?? "0.1.0",
    description: readString(metadata, "description") ?? plugin.id,
    author: metadata.author,
    homepage: metadata.homepage,
    repository: metadata.repository,
    license: metadata.license,
    keywords: metadata.keywords,
  };

  if (target === "claude") {
    return mergeRecords(
      withOptionalSurfacePaths(base, plugin, enabledSkills, target),
      readRecord(targetOptions, "manifest") ?? {}
    );
  }

  return mergeRecords(
    mergeRecords(withOptionalSurfacePaths(base, plugin, enabledSkills, target), {
      interface: renderCodexInterface(graph, plugin),
    }),
    readRecord(targetOptions, "manifest") ?? {}
  );
}

function renderCodexInterface(graph: BuildGraph, plugin: SourcePlugin): JsonRecord {
  const metadata = plugin.metadata;
  const ui = readRecord(metadata, "ui") ?? {};
  const author = readRecord(metadata, "author") ?? readRecord(graph.root.metadata, "owner") ?? {};
  const targetOptions = plugin.targets.codex.options;
  const interfaceOverrides = readRecord(targetOptions, "interface") ?? {};
  const color = readString(targetOptions, "color") ?? readString(ui, "color") ?? DEFAULT_CODEX_COLOR;
  const website = readString(ui, "websiteURL") ?? readString(metadata, "homepage") ?? readString(metadata, "repository");
  const capabilities = readStringArray(ui, "capabilities");
  const defaultPrompt = readStringArray(ui, "defaultPrompt");
  const screenshots = readStringArray(ui, "screenshots");

  const base: JsonRecord = {
    displayName: readString(ui, "displayName") ?? readString(metadata, "title") ?? titleize(plugin.id),
    shortDescription:
      readString(ui, "shortDescription") ?? readString(metadata, "description") ?? plugin.id,
    longDescription:
      readString(ui, "longDescription") ?? readString(metadata, "description") ?? plugin.id,
    developerName: readString(ui, "developerName") ?? readString(author, "name") ?? "Matt Galligan",
    category: readString(ui, "category") ?? readString(metadata, "category") ?? "Productivity",
    capabilities: [...(capabilities ?? ["Interactive", "Write"])],
    websiteURL: website,
    privacyPolicyURL: readString(ui, "privacyPolicyURL"),
    termsOfServiceURL: readString(ui, "termsOfServiceURL"),
    defaultPrompt: defaultPrompt ? [...defaultPrompt] : undefined,
    brandColor: color,
    composerIcon: readString(ui, "composerIcon"),
    logo: readString(ui, "logo"),
    screenshots: [...(screenshots ?? [])],
  };

  return mergeRecords(base, interfaceOverrides);
}

function withOptionalSurfacePaths(
  manifest: JsonRecord,
  plugin: SourcePlugin,
  enabledSkills: readonly SourceSkill[],
  target: TargetName
): JsonRecord {
  const withPaths: Record<string, JsonValue> = {};
  for (const [key, value] of Object.entries(manifest)) {
    if (value !== undefined) withPaths[key] = value;
  }

  if (enabledSkills.length > 0) withPaths.skills = "./skills/";
  if (target === "claude") {
    if (pluginHasPath(plugin, "commands")) withPaths.commands = "./commands";
    if (pluginHasPath(plugin, "agents")) withPaths.agents = "./agents";
    if (pluginHasPath(plugin, "hooks/hooks.json")) withPaths.hooks = "./hooks/hooks.json";
    if (pluginHasPath(plugin, ".mcp.json")) withPaths.mcpServers = "./.mcp.json";
  } else {
    if (pluginHasPath(plugin, "agents")) withPaths.agents = "./agents/";
    if (pluginHasPath(plugin, "hooks.json") || pluginHasPath(plugin, "hooks/hooks.json")) {
      withPaths.hooks = "./hooks.json";
    }
    if (pluginHasPath(plugin, ".mcp.json")) withPaths.mcpServers = "./.mcp.json";
    if (pluginHasPath(plugin, ".app.json")) withPaths.apps = "./.app.json";
  }

  return withPaths;
}

async function renderSkillFiles(
  plugin: SourcePlugin,
  skill: SourceSkill,
  target: TargetName,
  basePath: string
): Promise<readonly RenderedFile[]> {
  const sourceDir = dirname(skill.sourcePath);
  const relativeSkillDir = dirname(skill.pluginRelativePath);
  const targetSkillFile = join(basePath, relativeSkillDir, "SKILL.md");
  const rendered: RenderedFile[] = [
    textFile(targetSkillFile, renderSkillMarkdown(plugin, skill, target)),
  ];

  for (const file of await collectFiles(sourceDir)) {
    const relativeFile = relative(sourceDir, file);
    if (relativeFile === "SKILL.md") continue;
    rendered.push({
      path: join(basePath, relativeSkillDir, relativeFile),
      content: await readFile(file),
    });
  }

  return rendered;
}

function renderSkillMarkdown(plugin: SourcePlugin, skill: SourceSkill, target: TargetName): string {
  const metadata = skill.metadata;
  const targetOptions = skill.targets[target].options;
  const base = mergeRecords(stripSourceFrontmatter(skill.frontmatter), {
    name: readString(metadata, "id") ?? readString(skill.frontmatter, "name") ?? skill.id,
    description:
      readString(metadata, "description") ??
      readString(skill.frontmatter, "description") ??
      readString(metadata, "title") ??
      skill.id,
  });
  const references = metadata.references;
  const version = readString(metadata, "version") ?? readString(plugin.metadata, "version");
  const withReferences = references === undefined ? base : mergeRecords(base, { references });
  const withPortable =
    version === undefined ? withReferences : mergeRecords(withReferences, { metadata: { version } });
  const frontmatter = mergeRecords(
    withPortable,
    readRecord(targetOptions, "frontmatter") ?? {}
  );

  return stringifyMarkdown(frontmatter, skill.body);
}

async function copyPluginCompanionFiles(
  plugin: SourcePlugin,
  target: TargetName,
  basePath: string
): Promise<readonly RenderedFile[]> {
  const rendered: RenderedFile[] = [];
  const candidates =
    target === "claude"
      ? ["README.md", "commands", "agents", "hooks", ".mcp.json", "assets", "src"]
      : ["README.md", "agents", "hooks.json", ".mcp.json", ".app.json", "assets", "src"];

  for (const candidate of candidates) {
    const sourcePath = join(plugin.path, candidate);
    if (!(await exists(sourcePath))) continue;

    if (candidate === "hooks.json") {
      rendered.push(...(await copyPath(sourcePath, join(basePath, "hooks.json"))));
      continue;
    }

    rendered.push(...(await copyPath(sourcePath, join(basePath, candidate))));
  }

  if (target === "codex" && !pluginHasPath(plugin, "hooks.json") && pluginHasPath(plugin, "hooks/hooks.json")) {
    rendered.push(...(await copyPath(join(plugin.path, "hooks/hooks.json"), join(basePath, "hooks.json"))));
  }

  return rendered.filter((file) => !file.path.endsWith(".gitkeep"));
}

async function copyPath(sourcePath: string, targetPath: string): Promise<readonly RenderedFile[]> {
  const stats = await stat(sourcePath);
  if (stats.isFile()) {
    return [{ path: targetPath, content: await readFile(sourcePath) }];
  }

  const files: RenderedFile[] = [];
  for (const file of await collectFiles(sourcePath)) {
    files.push({
      path: join(targetPath, relative(sourcePath, file)),
      content: await readFile(file),
    });
  }
  return files;
}

async function collectFiles(root: string): Promise<readonly string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(path)));
    } else if (entry.isFile() && !entry.name.endsWith(".DS_Store")) {
      files.push(path);
    }
  }

  return files;
}

function pluginHasPath(plugin: SourcePlugin, path: string): boolean {
  try {
    validateSlug(plugin.id, "plugin id");
    const maybePath = join(plugin.path, path);
    return hasRenderableContent(maybePath);
  } catch {
    return false;
  }
}

function hasRenderableContent(path: string): boolean {
  if (!existsSync(path)) return false;
  const stats = statSync(path);
  if (stats.isFile()) return !isIgnoredCompanionFile(path);
  if (!stats.isDirectory()) return false;

  for (const entry of readdirSync(path)) {
    if (hasRenderableContent(join(path, entry))) return true;
  }

  return false;
}

function isIgnoredCompanionFile(path: string): boolean {
  const name = basename(path);
  return name === ".DS_Store" || name === ".gitkeep";
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") {
      return false;
    }
    throw error;
  }
}

function textFile(path: string, content: string): RenderedFile {
  return { path, content: textEncoder.encode(content) };
}

function titleize(value: string): string {
  return value
    .split("-")
    .filter((part) => part.length > 0)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join(" ");
}
